use crate::{app_data, legacy_image_files::resolve_legacy_image_path};
use image::{imageops::FilterType, DynamicImage, ImageFormat, ImageReader, Limits};
use sha2::{Digest, Sha256};
use std::{
    collections::HashMap,
    fs::{self, OpenOptions},
    io::{Cursor, Write},
    path::{Path, PathBuf},
    sync::{
        atomic::{AtomicU64, Ordering},
        Condvar, Mutex, OnceLock,
    },
    time::UNIX_EPOCH,
};

const CACHE_DIR_NAME: &str = ".clipstash-next-thumbnails-v1";
const CACHE_VERSION: u8 = 1;
const MAX_THUMBNAIL_EDGE: u32 = 320;
const MAX_SOURCE_BYTES: u64 = 64 * 1024 * 1024;
const MAX_SOURCE_PIXELS: u64 = 40_000_000;
const MAX_DECODE_ALLOC_BYTES: u64 = 48 * 1024 * 1024;
const MAX_CACHED_THUMBNAIL_BYTES: u64 = 2 * 1024 * 1024;
const DEFAULT_CACHE_MAX_BYTES: u64 = 128 * 1024 * 1024;
const MAX_CONCURRENT_GENERATIONS: usize = 2;
const PNG_SIGNATURE: &[u8; 8] = b"\x89PNG\r\n\x1a\n";

static GENERATION_SLOTS: OnceLock<(Mutex<usize>, Condvar)> = OnceLock::new();
static TEMP_FILE_SEQUENCE: AtomicU64 = AtomicU64::new(0);
static CACHE_STATES: OnceLock<Mutex<HashMap<PathBuf, CacheState>>> = OnceLock::new();
static CACHE_ACCESS_SEQUENCE: AtomicU64 = AtomicU64::new(0);

#[derive(Clone, Copy)]
struct ThumbnailCacheConfig {
    max_bytes: u64,
}

impl Default for ThumbnailCacheConfig {
    fn default() -> Self {
        Self {
            max_bytes: DEFAULT_CACHE_MAX_BYTES,
        }
    }
}

struct GenerationSlot;

struct CacheState {
    total_bytes: u64,
    entries: HashMap<PathBuf, CacheEntry>,
}

struct CacheEntry {
    bytes: u64,
    last_used: u64,
}

impl Drop for GenerationSlot {
    fn drop(&mut self) {
        let (count, available) = GENERATION_SLOTS.get_or_init(|| (Mutex::new(0), Condvar::new()));
        if let Ok(mut count) = count.lock() {
            *count = count.saturating_sub(1);
            available.notify_one();
        }
    }
}

fn acquire_generation_slot() -> Result<GenerationSlot, String> {
    let (count, available) = GENERATION_SLOTS.get_or_init(|| (Mutex::new(0), Condvar::new()));
    let mut count = count
        .lock()
        .map_err(|_| "图片缩略图生成队列锁已损坏".to_string())?;
    while *count >= MAX_CONCURRENT_GENERATIONS {
        count = available
            .wait(count)
            .map_err(|_| "图片缩略图生成队列锁已损坏".to_string())?;
    }
    *count += 1;
    Ok(GenerationSlot)
}

/// Returns a PNG thumbnail for a current-data-directory image. `expected_path` is required so
/// stale image records from a previous data directory cannot be used after switching directories.
#[tauri::command(async)]
pub async fn read_image_thumbnail_bytes(
    filename: String,
    expected_path: String,
) -> Result<tauri::ipc::Response, String> {
    tauri::async_runtime::spawn_blocking(move || {
        let data_dir = app_data::ready_app_data_dir_path()?;
        read_thumbnail_from_data_dir(
            &data_dir,
            &filename,
            &expected_path,
            ThumbnailCacheConfig::default(),
        )
        .map(tauri::ipc::Response::new)
    })
    .await
    .map_err(|err| format!("图片缩略图任务意外中断：{err}"))?
}

fn read_thumbnail_from_data_dir(
    data_dir: &Path,
    filename: &str,
    expected_path: &str,
    cache_config: ThumbnailCacheConfig,
) -> Result<Vec<u8>, String> {
    let (data_dir, image_path) = validate_current_image_path(data_dir, filename, expected_path)?;
    let source_metadata = fs::metadata(&image_path)
        .map_err(|err| format!("读取图片元数据失败：{}：{err}", image_path.display()))?;
    if source_metadata.len() > MAX_SOURCE_BYTES {
        return Err(format!(
            "图片文件过大，无法生成缩略图（超过 {} MiB）",
            MAX_SOURCE_BYTES / 1024 / 1024
        ));
    }

    let cache_dir = cache_dir_for_data_dir(&data_dir)?;
    let cache_path = cache_dir.join(cache_filename(&image_path, &source_metadata)?);
    if let Some(bytes) = read_cached_thumbnail(&cache_dir, &cache_path)? {
        return Ok(bytes);
    }

    let _slot = acquire_generation_slot()?;
    // A request that was waiting for a slot may have been generated by an earlier request.
    if let Some(bytes) = read_cached_thumbnail(&cache_dir, &cache_path)? {
        return Ok(bytes);
    }

    let source_bytes = fs::read(&image_path)
        .map_err(|err| format!("读取图片文件失败：{}：{err}", image_path.display()))?;
    if source_bytes.len() as u64 > MAX_SOURCE_BYTES {
        return Err("图片文件在读取期间超过缩略图大小上限".to_string());
    }
    let thumbnail = decode_thumbnail_png(&source_bytes)?;
    write_cache_atomically(&cache_dir, &cache_path, &thumbnail)?;
    register_cached_thumbnail_and_prune(
        &cache_dir,
        &cache_path,
        thumbnail.len() as u64,
        cache_config.max_bytes,
    )?;
    Ok(thumbnail)
}

pub(crate) fn validate_current_image_path(
    data_dir: &Path,
    filename: &str,
    expected_path: &str,
) -> Result<(PathBuf, PathBuf), String> {
    let data_dir = data_dir
        .canonicalize()
        .map_err(|err| format!("读取当前数据目录失败：{}：{err}", data_dir.display()))?;
    let images_dir = data_dir.join("images").canonicalize().map_err(|err| {
        format!(
            "读取当前图片目录失败：{}：{err}",
            data_dir.join("images").display()
        )
    })?;
    let image_path = resolve_legacy_image_path(&data_dir, filename)?;
    let image_path = image_path
        .canonicalize()
        .map_err(|err| format!("读取图片规范路径失败：{}：{err}", image_path.display()))?;
    if !image_path.starts_with(&images_dir) {
        return Err("图片路径不属于当前数据目录的 images 文件夹".to_string());
    }

    let expected_path = Path::new(expected_path.trim());
    if expected_path.as_os_str().is_empty() {
        return Err("图片预期路径不能为空".to_string());
    }
    let expected_path = expected_path
        .canonicalize()
        .map_err(|err| format!("读取图片预期路径失败：{}：{err}", expected_path.display()))?;
    if image_path != expected_path {
        return Err("图片路径已过期或不属于当前数据目录".to_string());
    }
    Ok((data_dir, image_path))
}

fn decode_thumbnail_png(source_bytes: &[u8]) -> Result<Vec<u8>, String> {
    let reader = ImageReader::new(Cursor::new(source_bytes))
        .with_guessed_format()
        .map_err(|err| format!("识别图片格式失败：{err}"))?;
    let (width, height) = reader
        .into_dimensions()
        .map_err(|err| format!("读取图片尺寸失败：{err}"))?;
    let pixels = u64::from(width) * u64::from(height);
    if width == 0 || height == 0 || pixels > MAX_SOURCE_PIXELS {
        return Err(format!("图片尺寸超过缩略图解码上限：{width}×{height}"));
    }

    // Decode a new reader after inspecting dimensions. For GIF/WebP the image crate exposes the
    // first frame as a DynamicImage, which is exactly the static list-thumbnail behavior wanted.
    let mut image_reader = ImageReader::new(Cursor::new(source_bytes))
        .with_guessed_format()
        .map_err(|err| format!("识别图片格式失败：{err}"))?;
    image_reader.limits(decode_limits());
    let image = image_reader
        .decode()
        .map_err(|err| format!("解码图片失败：{err}"))?;
    let thumbnail = resize_without_upscale(image, width, height);
    encode_png(&thumbnail)
}

fn decode_limits() -> Limits {
    let mut limits = Limits::default();
    limits.max_alloc = Some(MAX_DECODE_ALLOC_BYTES);
    limits
}

fn resize_without_upscale(image: DynamicImage, width: u32, height: u32) -> DynamicImage {
    if width <= MAX_THUMBNAIL_EDGE && height <= MAX_THUMBNAIL_EDGE {
        return image;
    }
    let (target_width, target_height) = if width >= height {
        (
            MAX_THUMBNAIL_EDGE,
            ((u64::from(height) * u64::from(MAX_THUMBNAIL_EDGE)) / u64::from(width)).max(1) as u32,
        )
    } else {
        (
            ((u64::from(width) * u64::from(MAX_THUMBNAIL_EDGE)) / u64::from(height)).max(1) as u32,
            MAX_THUMBNAIL_EDGE,
        )
    };
    image.resize_exact(target_width, target_height, FilterType::Triangle)
}

fn encode_png(image: &DynamicImage) -> Result<Vec<u8>, String> {
    let mut output = Cursor::new(Vec::new());
    image
        .write_to(&mut output, ImageFormat::Png)
        .map_err(|err| format!("编码 PNG 缩略图失败：{err}"))?;
    Ok(output.into_inner())
}

fn cache_dir_for_data_dir(data_dir: &Path) -> Result<PathBuf, String> {
    let data_dir = data_dir
        .canonicalize()
        .map_err(|err| format!("读取当前数据目录失败：{}：{err}", data_dir.display()))?;
    let cache_dir = data_dir.join(CACHE_DIR_NAME);
    if let Err(err) = fs::symlink_metadata(&cache_dir) {
        if err.kind() != std::io::ErrorKind::NotFound {
            return Err(format!(
                "读取缩略图缓存目录失败：{}：{err}",
                cache_dir.display()
            ));
        }
        match fs::create_dir(&cache_dir) {
            Ok(()) => {}
            Err(err) if err.kind() == std::io::ErrorKind::AlreadyExists => {}
            Err(err) => {
                return Err(format!(
                    "创建缩略图缓存目录失败：{}：{err}",
                    cache_dir.display()
                ));
            }
        }
    }
    let metadata = fs::symlink_metadata(&cache_dir)
        .map_err(|err| format!("读取缩略图缓存目录失败：{}：{err}", cache_dir.display()))?;
    if metadata.file_type().is_symlink() || !metadata.is_dir() {
        return Err("缩略图缓存目录不是安全的专用目录".to_string());
    }
    let canonical_cache_dir = cache_dir
        .canonicalize()
        .map_err(|err| format!("读取缩略图缓存目录失败：{}：{err}", cache_dir.display()))?;
    if canonical_cache_dir.parent() != Some(data_dir.as_path()) {
        return Err("缩略图缓存目录不在当前数据目录内".to_string());
    }
    Ok(canonical_cache_dir)
}

fn cache_filename(image_path: &Path, metadata: &fs::Metadata) -> Result<String, String> {
    let modified = metadata
        .modified()
        .map_err(|err| format!("读取图片修改时间失败：{}：{err}", image_path.display()))?
        .duration_since(UNIX_EPOCH)
        .map_err(|_| format!("图片修改时间早于 Unix Epoch：{}", image_path.display()))?;
    let mut digest = Sha256::new();
    digest.update([CACHE_VERSION]);
    digest.update(image_path.to_string_lossy().as_bytes());
    digest.update(metadata.len().to_le_bytes());
    digest.update(modified.as_secs().to_le_bytes());
    digest.update(modified.subsec_nanos().to_le_bytes());
    Ok(format!("{:x}.png", digest.finalize()))
}

fn read_cached_thumbnail(cache_dir: &Path, cache_path: &Path) -> Result<Option<Vec<u8>>, String> {
    let file_name = cache_path.file_name().and_then(|name| name.to_str());
    if !file_name.is_some_and(is_owned_thumbnail_filename) {
        return Err("缩略图缓存文件名不安全".to_string());
    }
    let metadata = match fs::symlink_metadata(cache_path) {
        Ok(metadata) => metadata,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(err) => {
            return Err(format!(
                "读取缩略图缓存失败：{}：{err}",
                cache_path.display()
            ));
        }
    };
    if metadata.file_type().is_symlink() || !metadata.is_file() {
        return Err("缩略图缓存文件不是安全的普通文件".to_string());
    }
    if metadata.len() > MAX_CACHED_THUMBNAIL_BYTES {
        remove_cached_thumbnail(cache_dir, cache_path)?;
        return Ok(None);
    }
    let bytes = match fs::read(cache_path) {
        Ok(bytes) => bytes,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(err) => {
            return Err(format!(
                "读取缩略图缓存失败：{}：{err}",
                cache_path.display()
            ));
        }
    };
    if bytes.starts_with(PNG_SIGNATURE) && cached_thumbnail_is_valid(&bytes) {
        record_cache_hit(cache_dir, cache_path, bytes.len() as u64)?;
        return Ok(Some(bytes));
    }
    remove_cached_thumbnail(cache_dir, cache_path)?;
    Ok(None)
}

fn cached_thumbnail_is_valid(bytes: &[u8]) -> bool {
    let reader = match ImageReader::new(Cursor::new(bytes)).with_guessed_format() {
        Ok(reader) => reader,
        Err(_) => return false,
    };
    let Ok((width, height)) = reader.into_dimensions() else {
        return false;
    };
    if width == 0 || height == 0 || width > MAX_THUMBNAIL_EDGE || height > MAX_THUMBNAIL_EDGE {
        return false;
    }
    let mut reader = match ImageReader::new(Cursor::new(bytes)).with_guessed_format() {
        Ok(reader) => reader,
        Err(_) => return false,
    };
    reader.limits(decode_limits());
    reader.decode().is_ok()
}

fn remove_cached_thumbnail(cache_dir: &Path, cache_path: &Path) -> Result<(), String> {
    match fs::remove_file(cache_path) {
        Ok(()) => {}
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
        Err(err) => {
            return Err(format!(
                "移除损坏缩略图缓存失败：{}：{err}",
                cache_path.display()
            ));
        }
    }
    remove_cache_index_entry(cache_dir, cache_path)?;
    Ok(())
}

fn write_cache_atomically(cache_dir: &Path, cache_path: &Path, bytes: &[u8]) -> Result<(), String> {
    let cache_name = cache_path
        .file_name()
        .and_then(|name| name.to_str())
        .filter(|name| is_owned_thumbnail_filename(name))
        .ok_or_else(|| "缩略图缓存文件名不安全".to_string())?;
    for _ in 0..32 {
        let sequence = TEMP_FILE_SEQUENCE.fetch_add(1, Ordering::Relaxed);
        let temp_path = cache_dir.join(format!(".{cache_name}.{sequence}.tmp"));
        let mut file = match OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temp_path)
        {
            Ok(file) => file,
            Err(err) if err.kind() == std::io::ErrorKind::AlreadyExists => continue,
            Err(err) => {
                return Err(format!(
                    "创建缩略图临时文件失败：{}：{err}",
                    temp_path.display()
                ));
            }
        };
        let result = (|| -> Result<(), std::io::Error> {
            file.write_all(bytes)?;
            file.flush()?;
            drop(file);
            fs::rename(&temp_path, cache_path)
        })();
        match result {
            Ok(()) => return Ok(()),
            Err(_err) if cache_path.is_file() => {
                let _ = fs::remove_file(&temp_path);
                return Ok(());
            }
            Err(err) => {
                let _ = fs::remove_file(&temp_path);
                return Err(format!(
                    "写入缩略图缓存失败：{}：{err}",
                    cache_path.display()
                ));
            }
        }
    }
    Err("创建缩略图临时文件失败：名称冲突过多".to_string())
}

fn cache_states() -> &'static Mutex<HashMap<PathBuf, CacheState>> {
    CACHE_STATES.get_or_init(|| Mutex::new(HashMap::new()))
}

fn next_cache_access() -> u64 {
    CACHE_ACCESS_SEQUENCE.fetch_add(1, Ordering::Relaxed)
}

fn scan_cache_state(cache_dir: &Path) -> Result<CacheState, String> {
    let mut state = CacheState {
        total_bytes: 0,
        entries: HashMap::new(),
    };
    for entry in fs::read_dir(cache_dir)
        .map_err(|err| format!("读取缩略图缓存目录失败：{}：{err}", cache_dir.display()))?
    {
        let entry = entry.map_err(|err| format!("读取缩略图缓存项失败：{err}"))?;
        let path = entry.path();
        let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
            continue;
        };
        if !is_owned_thumbnail_filename(name) {
            continue;
        }
        let metadata = match fs::symlink_metadata(&path) {
            Ok(metadata) => metadata,
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => continue,
            Err(err) => {
                return Err(format!(
                    "读取缩略图缓存元数据失败：{}：{err}",
                    path.display()
                ));
            }
        };
        if metadata.file_type().is_symlink() || !metadata.is_file() {
            continue;
        }
        if metadata.len() > MAX_CACHED_THUMBNAIL_BYTES {
            match fs::remove_file(&path) {
                Ok(()) => {}
                Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
                Err(err) => {
                    return Err(format!("清理过大缩略图缓存失败：{}：{err}", path.display()));
                }
            }
            continue;
        }
        state.total_bytes = state.total_bytes.saturating_add(metadata.len());
        state.entries.insert(
            path,
            CacheEntry {
                bytes: metadata.len(),
                last_used: next_cache_access(),
            },
        );
    }
    Ok(state)
}

fn record_cache_hit(cache_dir: &Path, cache_path: &Path, bytes: u64) -> Result<(), String> {
    let mut states = cache_states()
        .lock()
        .map_err(|_| "缩略图缓存状态锁已损坏".to_string())?;
    let Some(state) = states.get_mut(cache_dir) else {
        // Do not scan the directory on a cache hit. The first write below does one bounded
        // initialization scan, and all later writes update this in-memory index.
        return Ok(());
    };
    let last_used = next_cache_access();
    match state.entries.get_mut(cache_path) {
        Some(entry) => entry.last_used = last_used,
        None => {
            state.total_bytes = state.total_bytes.saturating_add(bytes);
            state
                .entries
                .insert(cache_path.to_path_buf(), CacheEntry { bytes, last_used });
        }
    }
    Ok(())
}

fn remove_cache_index_entry(cache_dir: &Path, cache_path: &Path) -> Result<(), String> {
    let mut states = cache_states()
        .lock()
        .map_err(|_| "缩略图缓存状态锁已损坏".to_string())?;
    let Some(state) = states.get_mut(cache_dir) else {
        return Ok(());
    };
    if let Some(entry) = state.entries.remove(cache_path) {
        state.total_bytes = state.total_bytes.saturating_sub(entry.bytes);
    }
    Ok(())
}

fn register_cached_thumbnail_and_prune(
    cache_dir: &Path,
    cache_path: &Path,
    bytes: u64,
    max_bytes: u64,
) -> Result<(), String> {
    let mut states = cache_states()
        .lock()
        .map_err(|_| "缩略图缓存状态锁已损坏".to_string())?;
    if !states.contains_key(cache_dir) {
        states.insert(cache_dir.to_path_buf(), scan_cache_state(cache_dir)?);
    }
    let state = states
        .get_mut(cache_dir)
        .expect("cache state was just initialized");
    // The atomic file write intentionally happens before this lock. Recheck after acquiring it:
    // a concurrent pruning pass may have removed this file while this writer was waiting.
    let actual_bytes = match fs::symlink_metadata(cache_path) {
        Ok(metadata) if !metadata.file_type().is_symlink() && metadata.is_file() => metadata.len(),
        Ok(_) => return Ok(()),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(err) => {
            return Err(format!(
                "读取新缩略图缓存元数据失败：{}：{err}",
                cache_path.display()
            ));
        }
    };
    if actual_bytes != bytes || actual_bytes > MAX_CACHED_THUMBNAIL_BYTES {
        match fs::remove_file(cache_path) {
            Ok(()) => {}
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
            Err(err) => {
                return Err(format!(
                    "移除异常缩略图缓存失败：{}：{err}",
                    cache_path.display()
                ));
            }
        }
        if let Some(previous) = state.entries.remove(cache_path) {
            state.total_bytes = state.total_bytes.saturating_sub(previous.bytes);
        }
        return Ok(());
    }
    if let Some(previous) = state.entries.insert(
        cache_path.to_path_buf(),
        CacheEntry {
            bytes: actual_bytes,
            last_used: next_cache_access(),
        },
    ) {
        state.total_bytes = state.total_bytes.saturating_sub(previous.bytes);
    }
    state.total_bytes = state.total_bytes.saturating_add(actual_bytes);

    while state.total_bytes > max_bytes {
        let Some((victim_path, victim_bytes)) = state
            .entries
            .iter()
            .min_by_key(|(path, entry)| (entry.last_used, *path))
            .map(|(path, entry)| (path.clone(), entry.bytes))
        else {
            break;
        };
        match fs::remove_file(&victim_path) {
            Ok(()) => {
                state.entries.remove(&victim_path);
                state.total_bytes = state.total_bytes.saturating_sub(victim_bytes);
            }
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => {
                state.entries.remove(&victim_path);
                state.total_bytes = state.total_bytes.saturating_sub(victim_bytes);
            }
            Err(err) => {
                return Err(format!(
                    "清理缩略图缓存失败：{}：{err}",
                    victim_path.display()
                ));
            }
        }
    }
    Ok(())
}

fn is_owned_thumbnail_filename(name: &str) -> bool {
    let Some(stem) = name.strip_suffix(".png") else {
        return false;
    };
    stem.len() == 64 && stem.bytes().all(|byte| byte.is_ascii_hexdigit())
}

#[cfg(test)]
mod tests {
    use super::*;
    use image::{codecs::gif::GifEncoder, Delay, Frame, GenericImageView, Rgba, RgbaImage};
    use std::{
        fs,
        sync::atomic::{AtomicU64, Ordering},
    };

    static TEST_SEQUENCE: AtomicU64 = AtomicU64::new(0);

    fn test_data_dir(label: &str) -> PathBuf {
        let sequence = TEST_SEQUENCE.fetch_add(1, Ordering::Relaxed);
        let data_dir = std::env::temp_dir().join(format!(
            "clipstash-next-thumbnail-{label}-{}-{sequence}",
            std::process::id()
        ));
        fs::create_dir_all(data_dir.join("images")).unwrap();
        data_dir
    }

    fn write_png(path: &Path, image: RgbaImage) {
        DynamicImage::ImageRgba8(image)
            .save_with_format(path, ImageFormat::Png)
            .unwrap();
    }

    fn source_path(data_dir: &Path, filename: &str) -> String {
        data_dir
            .join("images")
            .join(filename)
            .canonicalize()
            .unwrap()
            .display()
            .to_string()
    }

    fn thumbnail(data_dir: &Path, filename: &str) -> Vec<u8> {
        read_thumbnail_from_data_dir(
            data_dir,
            filename,
            &source_path(data_dir, filename),
            ThumbnailCacheConfig::default(),
        )
        .unwrap()
    }

    fn owned_cache_files(data_dir: &Path) -> Vec<PathBuf> {
        let cache_dir = cache_dir_for_data_dir(data_dir).unwrap();
        fs::read_dir(cache_dir)
            .unwrap()
            .filter_map(Result::ok)
            .map(|entry| entry.path())
            .filter(|path| {
                path.file_name()
                    .and_then(|name| name.to_str())
                    .is_some_and(is_owned_thumbnail_filename)
            })
            .collect()
    }

    fn remove_test_data_dir(data_dir: PathBuf) {
        fs::remove_dir_all(data_dir).unwrap();
    }

    #[test]
    fn large_png_is_reduced_to_320_without_changing_original_bytes() {
        let data_dir = test_data_dir("large");
        let source = data_dir.join("images/large.png");
        write_png(
            &source,
            RgbaImage::from_pixel(960, 480, Rgba([20, 40, 60, 255])),
        );
        let original = fs::read(&source).unwrap();

        let result = thumbnail(&data_dir, "large.png");
        let decoded = image::load_from_memory(&result).unwrap();
        assert_eq!(decoded.dimensions(), (320, 160));
        assert_eq!(fs::read(&source).unwrap(), original);
        remove_test_data_dir(data_dir);
    }

    #[test]
    fn small_images_are_not_upscaled_and_alpha_is_preserved() {
        let data_dir = test_data_dir("small-alpha");
        let source = data_dir.join("images/alpha.png");
        write_png(
            &source,
            RgbaImage::from_pixel(80, 40, Rgba([255, 20, 10, 0])),
        );

        let decoded = image::load_from_memory(&thumbnail(&data_dir, "alpha.png"))
            .unwrap()
            .to_rgba8();
        assert_eq!(decoded.dimensions(), (80, 40));
        assert_eq!(decoded.get_pixel(0, 0).0, [255, 20, 10, 0]);
        remove_test_data_dir(data_dir);
    }

    #[test]
    fn animated_gif_uses_its_first_frame() {
        let data_dir = test_data_dir("gif");
        let source = data_dir.join("images/animated.gif");
        let mut output = Vec::new();
        {
            let mut encoder = GifEncoder::new(&mut output);
            encoder
                .encode_frame(Frame::from_parts(
                    RgbaImage::from_pixel(12, 12, Rgba([230, 10, 10, 255])),
                    0,
                    0,
                    Delay::from_numer_denom_ms(50, 1),
                ))
                .unwrap();
            encoder
                .encode_frame(Frame::from_parts(
                    RgbaImage::from_pixel(12, 12, Rgba([10, 10, 230, 255])),
                    0,
                    0,
                    Delay::from_numer_denom_ms(50, 1),
                ))
                .unwrap();
        }
        fs::write(source, output).unwrap();

        let pixel = image::load_from_memory(&thumbnail(&data_dir, "animated.gif"))
            .unwrap()
            .to_rgba8()
            .get_pixel(0, 0)
            .0;
        assert!(
            pixel[0] > 200 && pixel[2] < 50,
            "expected first red frame, got {pixel:?}"
        );
        remove_test_data_dir(data_dir);
    }

    #[test]
    fn cache_is_reused_and_source_changes_create_a_new_entry() {
        let data_dir = test_data_dir("cache");
        let source = data_dir.join("images/source.png");
        write_png(
            &source,
            RgbaImage::from_pixel(640, 320, Rgba([220, 10, 10, 255])),
        );
        let first = thumbnail(&data_dir, "source.png");
        let first_cache = owned_cache_files(&data_dir);
        assert_eq!(first_cache.len(), 1);
        assert_eq!(thumbnail(&data_dir, "source.png"), first);
        assert_eq!(owned_cache_files(&data_dir), first_cache);

        write_png(
            &source,
            RgbaImage::from_pixel(660, 320, Rgba([10, 10, 220, 255])),
        );
        let second = thumbnail(&data_dir, "source.png");
        assert_ne!(second, first);
        assert_eq!(owned_cache_files(&data_dir).len(), 2);
        remove_test_data_dir(data_dir);
    }

    #[test]
    fn rejects_stale_directory_and_unsafe_filename() {
        let current_dir = test_data_dir("current");
        let old_dir = test_data_dir("old");
        write_png(
            &current_dir.join("images/image.png"),
            RgbaImage::from_pixel(2, 2, Rgba([1, 2, 3, 255])),
        );
        write_png(
            &old_dir.join("images/image.png"),
            RgbaImage::from_pixel(2, 2, Rgba([4, 5, 6, 255])),
        );
        let stale = read_thumbnail_from_data_dir(
            &current_dir,
            "image.png",
            &source_path(&old_dir, "image.png"),
            ThumbnailCacheConfig::default(),
        )
        .unwrap_err();
        assert!(stale.contains("过期"));
        let unsafe_name = read_thumbnail_from_data_dir(
            &current_dir,
            "../image.png",
            &source_path(&current_dir, "image.png"),
            ThumbnailCacheConfig::default(),
        )
        .unwrap_err();
        assert!(unsafe_name.contains("非法"));
        remove_test_data_dir(current_dir);
        remove_test_data_dir(old_dir);
    }

    #[test]
    fn cache_budget_evicts_only_owned_thumbnail_files() {
        let data_dir = test_data_dir("budget");
        let cache_dir = cache_dir_for_data_dir(&data_dir).unwrap();
        let first = cache_dir.join(format!("{}.png", "a".repeat(64)));
        let second = cache_dir.join(format!("{}.png", "b".repeat(64)));
        let unrelated = cache_dir.join("user-note.txt");
        fs::write(&first, vec![1; 12]).unwrap();
        fs::write(&second, vec![2; 12]).unwrap();
        fs::write(&unrelated, b"keep").unwrap();
        register_cached_thumbnail_and_prune(&cache_dir, &second, 12, 12).unwrap();
        assert_eq!(owned_cache_files(&data_dir).len(), 1);
        assert_eq!(fs::read(unrelated).unwrap(), b"keep");
        remove_test_data_dir(data_dir);
    }

    #[test]
    fn concurrent_first_requests_create_one_safe_cache_file() {
        let data_dir = test_data_dir("concurrent-first");
        let source = data_dir.join("images/source.png");
        write_png(
            &source,
            RgbaImage::from_pixel(960, 480, Rgba([20, 40, 60, 255])),
        );
        let expected_path = source_path(&data_dir, "source.png");
        let results = std::thread::scope(|scope| {
            let mut tasks = Vec::new();
            for _ in 0..8 {
                tasks.push(scope.spawn(|| {
                    read_thumbnail_from_data_dir(
                        &data_dir,
                        "source.png",
                        &expected_path,
                        ThumbnailCacheConfig::default(),
                    )
                }));
            }
            tasks
                .into_iter()
                .map(|task| task.join().unwrap().unwrap())
                .collect::<Vec<_>>()
        });
        assert!(results.windows(2).all(|pair| pair[0] == pair[1]));
        assert_eq!(owned_cache_files(&data_dir).len(), 1);
        remove_test_data_dir(data_dir);
    }

    #[test]
    fn corrupt_or_oversized_cache_is_removed_and_rebuilt() {
        let data_dir = test_data_dir("corrupt-cache");
        let source = data_dir.join("images/source.png");
        write_png(
            &source,
            RgbaImage::from_pixel(640, 320, Rgba([220, 10, 10, 255])),
        );
        let original_thumbnail = thumbnail(&data_dir, "source.png");
        let cache_path = owned_cache_files(&data_dir).pop().unwrap();
        let truncated = &original_thumbnail[..original_thumbnail.len() / 2];
        let dimensions = ImageReader::new(Cursor::new(truncated))
            .with_guessed_format()
            .unwrap()
            .into_dimensions()
            .unwrap();
        assert_eq!(dimensions, (320, 160), "fixture retains a valid PNG IHDR");
        fs::write(&cache_path, truncated).unwrap();
        assert_eq!(thumbnail(&data_dir, "source.png"), original_thumbnail);

        fs::write(
            &cache_path,
            vec![0; (MAX_CACHED_THUMBNAIL_BYTES + 1) as usize],
        )
        .unwrap();
        assert_eq!(thumbnail(&data_dir, "source.png"), original_thumbnail);
        remove_test_data_dir(data_dir);
    }

    #[test]
    fn failed_decode_leaves_no_thumbnail_or_temporary_cache_file() {
        let data_dir = test_data_dir("failure");
        let source = data_dir.join("images/bad.png");
        fs::write(&source, b"not an image").unwrap();
        assert!(read_thumbnail_from_data_dir(
            &data_dir,
            "bad.png",
            &source_path(&data_dir, "bad.png"),
            ThumbnailCacheConfig { max_bytes: 64 },
        )
        .is_err());
        let cache_dir = cache_dir_for_data_dir(&data_dir).unwrap();
        assert!(fs::read_dir(cache_dir).unwrap().next().is_none());
        remove_test_data_dir(data_dir);
    }
}
